### ISSUE TITLE
Workspace service

### ISSUE THREAD

**Issue by stephanebenayoun** [capsulajs/workspace-service#19]
## General description
Workspace is the core service of CapsulaHub, it is responsible for :
- Loading services and components that are included in its configuration (START)
- Allowing them to register themselves (REGISTER)
- Letting them communicate together (SERVICES/COMPONENTS)
- Getting their own configuration (CONFIG)

The Workspace has to be initialised with a token that will be used to get its own configuration.

The Workspace configuration will include the workspace name, services and components.
Each service will be described by its name, displayed name, the path to import it and eventually some options (including its config/state).
Each component will be described by its name, the path to import it and a node selector to specify where it should be rendered in the DOM.

#### Prerequisites
None.

#### Design description
https://github.com/capsulajs/workspace-service/pull/18

- [ ] Is it backward compatible ?
- [x] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Consideration
- At this stage, all services assume that the workspace is available under `window.workspace` 
- The services that composed the workspace are standalone and should include a bootstrap code that will call `registerService` method

### Test cases
https://github.com/capsulajs/workspace-service/pull/15

## Ready for implementation
- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes

## RoadMap
Each method of Workspace can be developed/merged separately, preferably in this order :
1. Start
2. Register service
3. Services
4. Components
5. Config
